name: HMCClaims
version: "${project.version}"
api-version: "${serverVersion}"
description: "A modern claims engine designed for performance, flexibility, and reliability."
authors:
  - Sqlace

main: com.hibiscusmc.hmcclaims.HMCClaims
loader: com.hibiscusmc.hmcclaims.HMCClaimsLoader

dependencies:
  server:
    HibiscusCommons:
      required: true
      join-classpath: true

    PlaceholderAPI:
      load: BEFORE
      required: false

    floodgate:
      load: BEFORE
      required: false